#!/bin/bash

mkdir -p "${XDG_CACHE_HOME:-'$HOME/.cache'}/nyaa"
temp="${XDG_CACHE_HOME:-'$HOME/.cache'}/nyaa"
url="https://nyaa.si"
dir=${NYAA_DIR:-"$HOME/Downloads"}
filter=1

trap "rm -rf $temp" SIGINT SIGTERM ERR EXIT

while getopts axd:q: flag; do
  case "${flag}" in
    a) filter=0;;
    x) url="https://sukebei.nyaa.si";;
    d) dir=${OPTARG};;
    q) query=${OPTARG};;
  esac
done

if [ -z "$query" ]; then
  query=$(pmenu -p "Search Torrent: ")
  if [ -z "$query" ]; then
    exit 0;
  fi
fi

query="$(echo $query | sed 's/ /+/g')"
curl -s "$url/?s=seeders&f=$filter&q=$query" > $temp/html

grep -o '<a href="/view/.*</a>' $temp/html | sed 's/<[^>]*>//g' > $temp/titles

results=$(wc -l $temp/titles | cut -d " " -f 1)
if [ $results -lt 1 ]; then
  echo No results
  exit 0
fi

grep -Po 'magnet:\?xt=urn:btih:[^"]*' $temp/html > $temp/magnets

magnet=$(paste $temp/titles $temp/magnets | pmenu | cut -f 2)
if [ -z "$magnet" ]; then
  echo Nothing selected
  exit 0
fi

mkdir -p $dir

if command -v webtorrent 2> /dev/null
then
  webtorrent "$magnet" -o $dir
else
  aria2c "$magnet" --seed-time 0 -d $dir
fi

echo Enjoy watching!

